# Generated by Django 3.1.2 on 2020-10-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201018_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Students',
            new_name='Student',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(),
        ),
    ]
