# Generated by Django 3.1.2 on 2020-10-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20201018_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courses',
            field=models.ManyToManyField(to='myapp.Course'),
        ),
    ]
