# Generated by Django 3.1.2 on 2020-10-20 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201018_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Student',
            new_name='student',
        ),
    ]
