# Generated by Django 3.1.2 on 2020-10-20 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20201019_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='student',
            new_name='Student',
        ),
    ]
