# Generated by Django 3.1.2 on 2020-12-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_student_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_image',
        ),
    ]
